### PR TITLE
Adds support for grouped data_frames

### PR DESCRIPTION
**Pull request by GShotwell**
This adds support for grouped dataframes as discussed in #82. I also created a new folder in `testthat/tests` to store the expected output of `skim()`.

### CODE REVIEW

**Comment by elinw** [comment]
@GShotwell could you update your branch? It is currently in conflict with master.

**Comment by GShotwell** [comment]
@elinw Whoops! I was importing %>% from the wrong package. Should have no conflicts now. We're probably going to have to make changes to the print method to ensure that it makes sense for grouped dataframes. Do you want to merge this in after the print method is stabilized? I'm happy either way

**Comment by elinw** [comment]
According to Travis the example isn't running successfully and there are a few other issues.  
Right now I feel like we should move ahead with things even though the print method is in flux.  This actually helps build more test cases for print.  For some reason I'm having a problem pulling down your branch but I'll figure it out.

**Comment by elinw** [comment]
@GShotwell I did `iris %>% dplyr::group_by(Species) %>% skim()`  and when I see the skim_print it doesn't show the grouping values.  Is that what you expect?

**Comment by elinw** [comment]
@GShotwell I sent a pull request to your repo that passes Travis.

**Comment by elinw** [comment]
This pull request is also incorporated in https://github.com/ropenscilabs/skimr/pull/122
along with tests.
@GShotwell @ShanEllis

**Comment by elinw** [comment]
Support for grouped data is in develop now.

**Pull request closed without merging**
