### PR TITLE
Clean up heading of README in repo

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by elinw** [comment]
Thank you! Some of these overlap with changes @jenniferthompson  had already sent, but some are different.  Let's see what happens when the tests run but we may end up have to clean up merge conflicts.

**Comment by elinw** [comment]
I'm not sure why you'd want to remove structural markup such as headings. 
Those things make i easier for both sighted and unsighted readers as well as spiders/bots to understand the structure of the document. Also  line lengths should always be 80 characters or shorter.

**Comment by ismayc** [comment]
Not sure that I follow? I was just hoping to make the package README look like other tidyverse community packages. Here is an example: https://raw.githubusercontent.com/tidyverse/ggplot2/master/README.Rmd . It makes the top of the README file for the repo cleaner.

Not sure I understand the line length comment here either as I just switched `output` to be a `github_document`.

**Comment by elinw** [comment]
I think what you are seeing there is special handling for tidyverse containing multiple packages.  Here
https://github.com/tidyverse/haven/  they don't even have the Rmd file in the repo from what I can find (I could have missed it).  I suspect they have some custom handling to make the tidyverse readme.  However it would be good to get rid of the TOC and also deleting all those trailing white spaces is really helpful.

**Comment by ismayc** [comment]
I am happy to tweak this to better fit your needs as I was only trying to assist with consistency. Just let me know what exactly needs done.

**Comment by ismayc** [comment]
Just to make sure we are on the same page here. I was attempting to remove the header that appears when you look at the README. If you only had a README.md file and no README.Rmd file I would have just suggested removing this at the top. Since the package has an Rmd file, I wanted to follow the practices that the `tidyverse` follows whenever the authors include a README.Rmd file.

screen shot 2018-02-17 at 2 33 10 pm

**Pull request closed without merging**
