### PR TITLE
Print concept groups Not for merging

### PR DESCRIPTION
**Pull request by elinw**
This merges the grouped data PR with the print refactor, so there is print handling of the grouped data.

### CODE REVIEW

**Comment by GShotwell** [comment]
Personally I think the `var_group_group...` method of displaying grouping variables is confusing. In my view it's better to display each groups value in its own column just like `dplyr::summarise()`.  In my view, `skim()` is mostly going to take the place of `summarise()  %>% spread()` for  a lot of people so we should try to match the summarize output if possible. What's the logic for collapsing the grouping information into one variable?

For an example of how it's a bit confusing try `mtcars %>% group_by(cyl, gear) %>% skim()` and compare it to `mtcars %>% group_by(gear, cyl) %>% skim()`.

**Comment by elinw** [comment]
First, saving space, these displays are extremely wide as is, and that's the source of a number of issues in the issue list. With grouping by3-4 variables with long-ish names just the grouping is going to take a lot of space on a laptop screen.  However we or the user can easily do step two and `separate_()`  to split them back into columns.
I actually don't think that you're right about the most common use case.  I'd just use summarize for a lot things where I know what variables I want and what specific statistics.  I think that the general idea is to get a quick overview of a data set especially when you have just gotten it or are looking at it for the first time and are getting ready to work with it. That's why you care about how many are missing etc and that is why it runs on all the variables by default.

**Comment by GShotwell** [comment]
I guess I was thinking that the current tidy way of getting a quick overview of your data is with a bunch of `summarize` or `summarize_each` calls. `str` is also a many-to-one function like `summarize`. To me whenever you make the printed output very different from the stored data you are risking confusion. This might be worth it when you are turning the long format into a wide format, but collapsing the grouping variables for screen space isn't worth the confusion IMO. 

The other thing to consider is that the collapsed output might not be tidy. It seems like the "observation" in this case is the statistic value, and the groups are variables and so should go in columns. Also the collapsed display puts a bunch of distinct information in one column. This untidiness isn't necessarily a bad thing (and tidiness is often in the eye of the beholder) but since the goal of the package as I understand it is to create a pipeable, tidy, summary function it might create some confusion if some of the print output isn't following the tidy data standard.

 I'm not sure I know how to use `separate` on printed output, do you have an example of that?

**Comment by elinw** [comment]
Remember the skim object is not changed by print.  So you just can keep piping the long object. The print is only for getting an overview, similar to `fivenum()` but more flexible, with a focus on looking good on the console right now (we have to work on the markdown rendering).      Do you think that people would normally be post-processing the print view?  so `data %>% skim() %>% skim_print() %>% something `  in addition to
`data %>% skim() %>% something `?  In that case it would make sense to add the `separate_()` since they probably would always want to do that.   
 
Part of what you are raising is the same issue as the significant figures one, some rows in "mean" should have no decimals, some should have 4, it's a problem we need to solve, but not really possible to do without converting them to strings. 
  I do get the sense that people would like a way to get a wide data set as well as a long one, and I think it might make sense to offer a pipeable function that will do that.    

I  originally was going to put separate_() in.  I can do it and see what people think.

**Comment by elinw** [comment]
I updated with` separate_()`, the test isn't updated to match which is why Travis will fail. I think basically it's a good idea to do it, but I'd like to find a way to make the impact on screen space smaller.

**Comment by elinw** [comment]
Maybe we could show the columns but just the first letter of the variables, since the full variable names are in the title.  Of course tibble always forces you to have minimum of 5 spaces.  So c and g instead of cyl and gear.

**Comment by elinw** [comment]
All of these changes plus tests and additional fixes are included in
https://github.com/ropenscilabs/skimr/pull/122
So I am going to close this issue
@GShotwell @michaelquinn32 @earino

**Pull request closed without merging**
