### PR TITLE
Create summary method for skim class

### PR DESCRIPTION
**Pull request by ConnorKirk**
Hi, 

This attempts  issue #156 

I expect it needs some additional development before it's ready. I'd appreciate feedback on what could be done.

### CODE REVIEW

**Comment by elinw** [comment]
Cool start on this! I will take a look at it as soon as I can.

**Comment by elinw** [comment]
Hi Colin, I sent you a PR with some proposed changes.  This is a great start.  I'm thinking that if we can make this solid maybe we would just use it in the print.skim_df methods to allow us to make displaying that part optional. 

I see two main issues.
First, the frequency of the types is not the correct frequency since it is counting all of the rows in the skim_df instead of one row per variable.  I think you should be able to deal with that using dplyr. 

Second, from my experience normally a summary returns a list, sometimes with attributes.  Then a second method, e.g. `print.summary.skim_df` would be used to assemble the pieces into something that prints.  So basically the last part of your function where you are putting it all together with  `cat()` would go into that new function.  That gives the user a lot of flexibility to pull out specific pieces of the summary which is really nice to be able to do.

**Comment by elinw** [comment]
Also it would be great if you could update your branch to be in sync with the development branch.

**Comment by ConnorKirk** [comment]
Thanks elinw. Your suggestions are a good ones. I'll make the changes and resubmit.

**Comment by elinw** [comment]
Great, it should be that if you update your branch they automatically come through to the PR.

**Comment by elinw** [comment]
Hi Connor,
One thing I also wanted to mention is that you need to make your function signature match the generic one for summary() which is 1summary(object, ...)`.  You can see this in the Travis Ci report.

**Comment by ConnorKirk** [comment]
Thanks elinw! That also helped me solve my problem of the print method not working for the summary_skim object. I've hit one more snag, but I should have it sorted soon. I'll check it in once I've cleared the issue.

Thanks for all of your help (and time)!

**Comment by elinw** [comment]
Note that the code coverage statistics are always slightly off when you add a new file. This is not a problem.

**Pull request merged**
