### PR TITLE
Make ordered factors print like factors.

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by michaelquinn32** [comment]
Hi Elin!

I think this moves us in the right direction, but I want to hold off on this for a little bit. It continues supporting a fixed map between a particular set of classes and the output that skim generates. I'm trying to think of ways to make this more generic. If the underlying object contains classes not explicitly defined in the current print method, I still think we should have a way of printing the result.

**Comment by elinw** [comment]
The ordered factors are a bit of a special case since they are factors and we're already supporting factors.  I agree with holding off on supporting logical, complex etc until we have a better approach.

I'd really like to see a more generic handling so that, among other things, we can support new types and statistics.  It seems to me that if we are going to have different outputs for different types that we should have a similar architecture as for skim_v. 

It's frustrating now that you can see the unsupported types when using the print method, and that's generating a lot of issue reports.

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/issues/76  is actually also related to print.

**Comment by elinw** [comment]
I created a concept that isn't finished but this gives an idea of what the functions for individual types might look like.  https://github.com/ropenscilabs/skimr/blob/printconcept/R/skim_print.R
I'd like to change "hist" to "spark" or "visualization" so that the handling could be more generic if people follow the rules on naming.

**Comment by earino** [comment]
i like calling it something like "visualization" @elinw. That feels right. Do we ever imagine we would have multiple visualizations for any one column? (If I'm remembering how this works.)

**Comment by elinw** [comment]
@earino I made a PR for adding a spark line graph for time series.   I also noticed that Hadley has spark boxplot in his list of potential enhancements.

**Comment by elinw** [comment]
This is replaced with the skim_print() refactoring.

**Pull request closed without merging**
