### PR TITLE
Support for knitr kable and pander

### PR DESCRIPTION
**Pull request by michaelquinn32**
This is just a start. The knitr output is untested and the docs are in rough shape.

### CODE REVIEW

**Comment by elinw** [comment]
I like this concept a lot.

**Comment by jorgesinval** [comment]
Can you explain how to use the function `skimr:::skim_print`?

**Comment by elinw** [comment]
That's not in this branch any more.   Let's discuss it in your issue.

I wanted to note for anyone testing here that I'm having to explicitly put format="html" or format = "latex"   e.g. `skim(iris) %>% skimr:::kable(format = "latex")`   
  and it's outputting raw rather then rendering.   But I'm still working my way through the code.  The html looks great inside a notebook.

**Comment by jorgesinval** [comment]
Using your example gives me:

`Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : object 'kable' not found`.

**Comment by elinw** [comment]
Silly me also on my earlier comment about rendering, I forgot to put `results='asis'` ins the chunk options.

@jorgesinval did you explicitly load knitr in your rmarkdown?

**Comment by jorgesinval** [comment]
@elinw , yes I loaded it. I try the following code:

`
```{r, results='asis'}
devtools::install_github("ropenscilabs/skimr", force = T)
library(skimr)
library(knitr)
skim(iris) %>% skmir:::kable(format = "html")
```
`
And I get this:

`Error: 'spark_bar' is not an exported object from 'namespace:pillar' `

**Comment by jorgesinval** [comment]
Is it working?

**Comment by elinw** [comment]
Yes, if you use the develop branch you can do e.g. skim(iris) %>% kable() but you do need to use `results=asis` in your chunk with kable.  With pander() the asis option does not work in all cases (if the table is split).  However the other pander formatting does work.   In general you are likely to also have to set the font if you want the spark graphs to work correctly, but it depends a lot on your OS and what document type you are knitting to.

**Comment by jorgesinval** [comment]
Yes, it's working! Nice, very nice!

**Comment by andbarker** [comment]
Awesome! 
What font(s) do the spark graphs use?

**Comment by jorgesinval** [comment]
See: https://github.com/holman/spark

**Pull request merged**
